#spring:
#  application:
#    name: zuul-server
#server:
#  port: 5555
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8001}/eureka/
#  instance:
#    prefer-ip-address: true
#zuul:
#  routes:
#    client-a:
#      path: /client/**
#      serviceId: client-a
###默认情况下很多端点是不允许访问的，会返回401:Unauthorized
#management:
#  security:
#    enabled: false
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      access-token-uri: http://localhost:7777/uaa/oauth/token #令牌端点
#      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize #授权端点
#      client-id: zuul_server #OAuth2客户端ID
#      client-secret: secret #OAuth2客户端密钥
#    resource:
#      jwt:
#        key-value: springcloud123 #使用对称加密方式，默认算法为HS256

spring:
  application:
    name: zuul-gate
#  zipkin:
#    base-url: http://10.10.8.2:9050
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true #使用IP注册
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://localhost:8001/eureka/
###actuator监控点 start####
#endpoints:
#  health:
#    sensitive: false
#    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
#management:
#  security:
#    enabled: false
###actuator监控点 end####
zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  routes:
    uaa:
      path: /uaa/**
      sensitiveHeaders:
      serviceId: auth-server
      strip-prefix: false
    client-a:
      path: /client-a/**
      strip-prefix: false
      sensitiveHeaders:
      serviceId: client-a
  add-proxy-headers: true
security:
#  basic:
#    enabled: false
  oauth2:
#    client:
#      access-token-uri: http://127.0.0.1:8080/uaa/oauth/token ##网关的地址
#      user-authorization-uri: http://127.0.0.1:8080/uaa/oauth/authorize
#      client-id: webapp
    resource:
      user-info-uri:  http://127.0.0.1:8080/uaa/user
      prefer-token-info: false
##############end#####################
####超时配置####
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 600000
###超时配置###