spring:
  application:
    name: auth-server
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: comma520
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
server:
  port: 9030
  servlet:
    contextPath: /uaa #web基路径

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8001/eureka/
  instance:
    prefer-ip-address: true
logging:
  config: classpath:logback.xml
  level:
    org:
      springframework:
        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

#security:
#  oauth2:
#    resource:
#      filter-order: 3
